version = 1

[[analyzers]]
name = "rust"
enabled = true

[analyzers.meta]
msrv = "1.30.0"

[[analyzers]]
name = "javascript"
enabled = true

exclude_patterns = [
  "apps/oxidize/src/prisma.rs",
  "apps/tnt/src/lib/locales/",
  "**/node_modules/",
]
